name: Pre-Release CI

on:
  push:
    branches:
      - 'release-plz-*'

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: '-D warnings'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build with Cargo
        run: cargo build

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CRD"
